name: Self Audit (1st level)
description: A preliminary check that is done by the project authors before requesting 3rd party audit
title: "[Scope]: "
labels: ["stage:first"]
body:
  - type: input
    id: i10
    attributes:
      label: Source branch
      description: What is the source branch to be audited?
      placeholder: ex. github.com/allinbits/something-someting
    validations:
      required: false
  - type: markdown
    id: i20
    attributes:
      value: |
        The following section is a checklist of actions that should be perfomrmed as a pre-requisite
        for a audit process
  - type: checkboxes
    id: i40
    attributes:
      label: Automation
      description: checks that should be enabled on the target repositories
      options:
        - label: golangci-lint with the following configuration (TODO permalink to the config)
          required: false
        - label: Codecov (?)
          required: false
        - label: Codeclimate (?)
          required: false
  - type: checkboxes
    id: i60
    attributes:
      label: Documenation
      description: this is the checklist for documentation
      options:
        - label: Module level documetation
          required: false
        - label: ADRs
          required: false
        - label: General documentation (portal?)
          required: false
  - type: checkboxes
    id: i80
    attributes:
      label: Network
      description: checklist for network launch
      options:
        - label: Simulation executed (2w?)
          required: false
  - type: checkboxes
    id: i100
    attributes:
      label: General
      description: general checklist
      options:
        - label: No github CVE warnings
          required: false



