name: Self Audit (1st level)
description: A preliminary check that is done by the project authors before requesting 3rd party audit
title: "[Scope]: "
labels: ["stage:first"]
body:
  - type: input
    id: source
    attributes:
      label: Source branch
      description: What is the source branch to be audited?
      placeholder: ex. github.com/allinbits/something-someting
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        The following section is a checklist of actions that should be perfomrmed as a pre-requisite
        for a audit process
  - type: markdown
      attributes:
        value: ### Automatic Checks
  - type: checkboxes
    id: terms
    attributes:
      label: Automatic checks
      description: checks that should be enabled on the target repositories
      options:
        - label: golangci-lint with the following configuration (TODO permalink to the config)
          required: false
        - label: Codecov (?)
          required: false
        - label: Codeclimate (?)
          required: false
  - type: markdown
    attributes:
      value: ### Documentation
  - type: checkboxes
    id: terms
    attributes:
      label: Documenation checklist
      description: this is the checklist for documentation
      options:
        - label: Module level documetation
          required: false
        - label: ADRs
          required: false
        - label: General documentation (portal?)
          required: false
  - type: markdown
    attributes:
      value: ### Network specific
  - type: checkboxes
    id: terms
    attributes:
      label: network checklist
      description: checklist for network launch
      options:
        - label: Module level documetation
          required: false
        - label: Simulation executed (2w?)
          required: false
  - type: markdown
    attributes:
      value: ### General
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: No github CVE warnings
          required: false



